In [50]:
import numpy as np
a1=np.array([[2,3,5],
            [3,43,53]])
b1=np.array([[1,0,2],
            [3,8,3]])
#print(a1.shape)
#a1=a1.reshape(3,2)
#print(b1.shape)
#print(a1.ndim)
#print(a1.size)
#print(a1.dtype)
#print(np.sum(a1))
#print(np.sum(a1,axis=1)) for row 
#print(a1[1][1])
#print(a1[1,1])
#print(a1[0:,2])
#print(a1+2)
#print(a1*2)
#print(np.dot(b1,a1))
print(a1,b1)
a=[1,6,5]
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.min(a))
print(np.max(a))

[[ 2  3  5]
 [ 3 43 53]] [[1 0 2]
 [3 8 3]]
12
4.0
5.0
1
6
